### ISSUE TITLE
npm run build  error

### ISSUE THREAD

**Issue by dgo2dance** [StephenChou1017/react-big-scheduler#201]
after clone  and  npm install
npm run build    get  the  error     why

Cleaning...
D:\02.my-work\01.across\02\react-big-scheduler\scripts\build.js:11
  throw err;
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buf
er. Received an instance of Error
[90m    at validChunk (_stream_writable.js:281:10)[39m
[90m    at WriteStream.Writable.write (_stream_writable.js:316:21)[39m
    at build (D:\02.my-work\01.across\02\react-big-scheduler\scripts\build.js:69:20)
Emitted 'error' event on WriteStream instance at:
[90m    at errorOrDestroy (internal/streams/destroy.js:108:12)[39m
[90m    at validChunk (_stream_writable.js:284:5)[39m
[90m    at WriteStream.Writable.write (_stream_writable.js:316:21)[39m
    at build (D:\02.my-work\01.across\02\react-big-scheduler\scripts\build.js:69:20) {
  code: [32m'ERR_INVALID_ARG_TYPE'[39m
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-big-scheduler@0.2.5 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-big-scheduler@0.2.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-06-02T09_15_46_416Z-debug.log

**Comment by alizaidi606** [comment]
I am having the exact same issue.

**Comment by balint-kancsar** [comment]
Any news on this?
