### ISSUE TITLE
By using your code, I'm getting error while installing node modules. Can you please help me with this issue.

### ISSUE THREAD

**Issue by teja-94** [StephenChou1017/react-big-scheduler#229]
Hi @StephenChou1017 ,
Greetings for the day.!

**My current Node version - v15.11.0 & Npm Version- v 7.8.0**

Since Friday, I have tried so many times still I'm getting this type of error. Please take a look and give me the reason behind this error.

C:\Users\Lenovo\Downloads\react-big-scheduler-master>npm install
npm ERR! code 1
npm ERR! path C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\Lenovo\\Downloads\\react-big-scheduler-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.11.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python39\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lenovo\\Downloads\\react-big-scheduler-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\Lenovo\Downloads\react-big-scheduler-master\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.11.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Local\npm-cache\_logs\2021-04-05T05_50_30_124Z-debug.log

**Comment by tranquanglk94** [comment]
I think you can remove package-lock.json and node_module. Then run "npm install" again.

**Comment by eric-taix** [comment]
Removing `package-lock.json` and `node_module` worked for me. Thanks
