### ISSUE TITLE
page is not loading

### ISSUE THREAD

**Issue by shaytoMoonActive** [StephenChou1017/react-big-scheduler#265]
Trying to open : https://stephenchou1017.github.io/scheduler/#/
and not seeing anything (blank page)
here is the error in the console :
to load resource: the server responded with a status of 403 ()
react.production.min.js:1 Failed to load resource: the server responded with a status of 403 ()
moment.min.js:1 Failed to load resource: the server responded with a status of 403 ()
zh-cn.js:1 Failed to load resource: the server responded with a status of 403 ()
polyfill.min.js:1 Failed to load resource: the server responded with a status of 403 ()
bundle.js:1 Uncaught ReferenceError: React is not defined
at Object. (bundle.js:1:975)
at n (bundle.js:1:110)
at Object. (bundle.js:32:839950)
at n (bundle.js:1:110)
at Object. (bundle.js:32:839905)
at n (bundle.js:1:110)
at bundle.js:1:902
at bundle.js:1:913

**Comment by ansulagrawal** [comment]
@shaytoMoonActive try this library its same and updated version for same: https://github.com/ansulagrawal/react-big-schedule
contributions are welcome.
