### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by asadmakram** [StephenChou1017/react-big-scheduler#89]
I have pulled the master branch and try running npm install, and got the following errors in log. can you please help me figure out what's wrong?

node version: v10.15.0
npm version: 6.5.0

15692 verbose stack Error: sha512-zPvPA3T7P6M+0iNsgX+iAcAz4GshKrowtQBHHc/28tVsBc8jK7VRCNX+2GEcoE6zDB6XqXhcyiUWPVZY6C70Cg== integrity checksum failed when using sha512: wanted sha512-zPvPA3T7P6M+0iNsgX+iAcAz4GshKrowtQBHHc/28tVsBc8jK7VRCNX+2GEcoE6zDB6XqXhcyiUWPVZY6C70Cg== but got sha512-rh+KuAW36YKo0vClhQzLLveoj8FwPJNu65xLb7Mrt+eZht0IPT0IXgSv8gcMegZ6NvjJUALf6Mf25POlMwD1Fw==. (13865 bytes)
15692 verbose stack     at Transform.on (/usr/lib/node_modules/npm/node_modules/ssri/index.js:328:19)
15692 verbose stack     at Transform.emit (events.js:187:15)
15692 verbose stack     at endReadableNT (_stream_readable.js:1094:12)
15692 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
15693 verbose cwd /home/asad/Desktop/learning/react/react-big-scheduler
15694 verbose Linux 4.15.0-43-generic
15695 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
15696 verbose node v10.15.0
15697 verbose npm  v6.5.0
15698 error code EINTEGRITY
15699 error Verification failed while extracting url-parse@1.3.0:
15699 error Verification failed while extracting url-parse@1.3.0:
15699 error sha512-zPvPA3T7P6M+0iNsgX+iAcAz4GshKrowtQBHHc/28tVsBc8jK7VRCNX+2GEcoE6zDB6XqXhcyiUWPVZY6C70Cg== integrity checksum failed when using sha512: wanted sha512-zPvPA3T7P6M+0iNsgX+iAcAz4GshKrowtQBHHc/28tVsBc8jK7VRCNX+2GEcoE6zDB6XqXhcyiUWPVZY6C70Cg== but got sha512-rh+KuAW36YKo0vClhQzLLveoj8FwPJNu65xLb7Mrt+eZht0IPT0IXgSv8gcMegZ6NvjJUALf6Mf25POlMwD1Fw==. (13865 bytes)
15700 verbose exit [ 1, true ]

**Comment by StephenChou1017** [comment]
@asadmakram 
Yes, I reappear this issue with node@10.15.0 and npm@6.5.0, I npm install successfully after I remove the package-lock.json, and the examples work fine after I npm run example.
